services:
  postgres:
    container_name: y-go-api
    image: bitnami/postgresql:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "root"
      POSTGRES_DB: "root"
    ports:
      - "5500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
